const generalActionTypes = {
    SET_COLLABORATION_DATA: 'SET_COLLABORATION_DATA',
    SET_LOGIN_ERROR: 'SET_LOGIN_ERROR',
    SET_DISCOUNT_DATA: 'SET_DISCOUNT_DATA', // For storing discount images
    SET_DISCOUNT_CODES: 'SET_DISCOUNT_CODES',
    SET_CUSTOMER_GALLERY: 'SET_CUSTOMER_GALLERY',
    SET_FREE_PRODUCT_INFO: 'SET_FREE_PRODUCT_INFO'
};

export default generalActionTypes;