const productActionTypes = {
    SET_PRODUCTS_DATA: 'SET_PRODUCTS_DATA',
    SET_PAGINATION_NUMBER: 'SET_PAGINATION_NUMBER',
    SET_PRODUCT_LIST: 'SET_PRODUCT_LIST',
    SET_PRODUCT_TYPE: 'SET_PRODUCT_TYPE',
    SET_GENRE_TYPE: 'SET_GENRE_TYPE',
    SET_PRODUCT_CATEGORIES: 'SET_PRODUCT_CATEGORIES',
    SET_GENRE_CATEGORIES: 'SET_GENRE_CATEGORIES'
};

export default productActionTypes;