const userActionTypes = {
    SET_USER_DETAILS: 'SET_USER_DETAILS',
    ADD_NEW_ADDRESS: 'ADD_NEW_ADDRESS',
    SET_USER_ADDRESSES: 'SET_USER_ADDRESSES',
    SET_SELECTED_ADDRESS_INDEX: 'SET_SELECTED_ADDRESS_INDEX',
    SET_USER_INVOICES: 'SET_USER_INVOICES'
};

export default userActionTypes;